---
- name: Nginx | Setup EPEL
  ansible.builtin.shell:
    cmd: amazon-linux-extras install epel -y && touch /tmp/epel-released
    creates: /tmp/epel-released

- name: Nginx | Install Dependencies
  ansible.builtin.yum:
    name: '{{ certbot_yum_dependencies }}'
    update_cache: true
    state: present

- name: Nginx | Copy Config
  ansible.builtin.template:
    src: './files/nginx.conf.j2'
    dest: '/etc/nginx/nginx.conf'
    owner: root
    group: root
    mode: '0644'
  notify: 'Reload Nginx'

- name: Nginx | Copy Certbot Script
  ansible.builtin.copy:
    src: './files/cert.sh'
    dest: '/home/ec2-user/cert.sh'
    owner: 'ec2-user'
    group: 'ec2-user'
    mode: '0755'
